name: CityBuildPlugin
version: ${project.version}
main: de.lowtime.sg.Main
author: lowtime
commands:
  invsee:
    permission: invsee.use
    permission-message: §7CityBuild | Dir fehlt die Berechtigung!
  heal:
    permission: heal.use
    permission-message: §7CityBuild | Dir fehlt die Berechtigung!
  tpa:
    permission: tpa.use
    permission-message: §7CityBuild | Dir fehlt die Berechtigung!
  tpahere:
    permission: tpahere.use
    permission-message: §7CityBuild | Dir fehlt die Berechtigung!
  tpaaccept:
    permission: tpaacept.use
    permission-message: §7CityBuild | Dir fehlt die Berechtigung!
  ping:
    permission: ping.use
    permission-message: §7CityBuild | Dir fehlt die Berechtigung!
  fly:
    permission: fly.use
    permission-message: §7CityBuild | Dir fehlt die Berechtigung!
